### ISSUE TITLE
strTemplate erroring our due to toLowercase()

### ISSUE THREAD

**Issue by gregswift** [razee-io/MustacheTemplate#144]
**Describe the bug**
I created a new MTP to test something this weekend and it fails when it tries to do an strTemplate, which is where I started case the new test was built around iterations.  Using the iterations and using `spec.templates` instead of `spec.strTemplates` we ran into this error. (see copypaste)  Then we preceded to check out MTPs to try to identify the root. The other MTP has no errors, but also havent hcnaged in a few days.

**To Reproduce**
1. Create new MTP using a strTemplate
2. Apply MTP to cluster
3. Check MTP status

**Expected behavior**
I would expect the MTP to render out the desired resource.

**Copypasta**

```
---
apiVersion: "deploy.razee.io/v1alpha1"
kind: MustacheTemplate
metadata:
  name: es-test-output
  namespace: default
  labels:
    app: elasticsearch
spec:
  envFrom:
  - configMapRef:
      name: elasticsearch-defaults
  strTemplates:
  - |
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: es-test-output
      data:
        es-bqs: "{{{bulk-queue-size}}}"
```
``
`Status:
  Razee - Logs:
    Error:
      a6da6942d565f259493df061edfc0ad33de6f3ee:  Cannot read property 'toLowerCase' of undefined
```

**Kubernetes Version (kubectl version):**
 - Client: 1.16
 - Server: 1.16

**Additional context**
https://github.com/razee-io/MustacheTemplate/blob/a84cd8a46d440dfb0dedddde9769de0deef77f36/src/MustacheTemplateController.js#L65

**Comment by gregswift** [comment]
So.. i went to an environment where we arent running MTP 0.8.1.. its running 0.7.4 and I'm actually seeing the same thing.

Dug a bit further and found this 

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at MustacheTemplateController.applyChild (/home/node/node_modules/@razee/razeedeploy-core/lib/CompositeController.js:74:26)
    at MustacheTemplateController.added (/home/node/node_modules/@razee/razeedeploy-core/lib/BaseTemplateController.js:41:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MustacheTemplateController._added (/home/node/node_modules/@razee/razeedeploy-core/lib/BaseController.js:146:5)
    at async MustacheTemplateController.execute (/home/node/node_modules/@razee/razeedeploy-core/lib/BaseController.js:94:9)
    at async EventHandler.eventHandler (/home/node/node_modules/@razee/kubernetes-util/lib/EventHandler.js:78:12)
```
Which points to this line: https://github.com/razee-io/razeedeploy-core/blob/master/lib/CompositeController.js#L74

so upon further evaluation the problem ended up being that i had a `-` starting the resource in the strTemplate.

I had: 

```
  strTemplates:
  - |
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: es-test-output
      data:
        es-bqs: "{{{bulk-queue-size}}}"

```

This solved it
```
  strTemplates:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: es-test-output
    data:
      es-bqs: "{{{bulk-queue-size}}}"

```
