### ISSUE TITLE
Conditional Functionality in MustacheTemplates

### ISSUE THREAD

**Issue by dgr237** [razee-io/MustacheTemplate#16]
The use case that we are wanting to acheive is to be able to use a MustacheTemplate to conditionally create a remote resource: 
```
apiVersion: "kapitan.razee.io/v1alpha1"
kind: MustacheTemplate
metadata:
  name: conditional-nginx-install
  namespace: nginx
spec:
  env:
  - name: nginx-version
    optional: true
    valueFrom:
      configMapKeyRef:
         name: additional-services
         namespace: core
         key: nginx-version
  templates:
    - apiVersion: "kapitan.razee.io/v1alpha1"
      kind: RemoteResource
      metadata:
        name: nginx-remote-resource
        namespace: nginx
     spec:
        requests:
           - options:
  	      url: https://<source_repo_url>/nginx/{{nginx-version}}/install.yaml
```
The logic which I am trying to achieve is such that if the additional-services configmap does not exist or if the nginx-version is not configured then the remote resource will not be created.

One suggestion is to add additional attributes under spec:

render-templates-if-not-null: nginx-version

This would alter the mustache template to be:

{{^nginx-version}}
// Template from above
{{/nginx-version}}

This would mean a remote resource is not created with a 404 error when trying to create the remote resource. 

Ideally the logic should be that if the config map additional-services is deleted or the nginx-version attribute is removed then the nginx-remote-resource would be deleted and the child objects would also be deleted.

Let me know if you have any questions.

**Comment by alewitt2** [comment]
circling back to this issue. I think we may now have a solution for you by using the new string templates. If you get creative you can use strTemplate with mustache techniques to accomplish what you are looking for:

```
apiVersion: "deploy.razee.io/v1alpha2"
kind: MustacheTemplate
metadata:
  name: conditional-nginx-install
  namespace: nginx
spec:
  env:
  - name: nginx-version
    optional: true
    valueFrom:
      configMapKeyRef:
         name: additional-services
         namespace: core
         key: nginx-version
  strTemplates:
    - |
      {{#nginx-version}}
      apiVersion: "deploy.razee.io/v1alpha2"
      kind: RemoteResource
      metadata:
        name: nginx-remote-resource
        namespace: nginx
      spec:
        requests:
          - options:
              url: https://<source_repo_url>/nginx/{{nginx-version}}/install.yaml
      {{/nginx-version}}
```

feel free to re-open issue if you have more questions.
