### ISSUE TITLE
Support merging (json) values from two configmap keys

### ISSUE THREAD

**Issue by simonkotwicz** [razee-io/MustacheTemplate#289]
**Is your feature request related to a problem? Please describe.**
We are trying to simplify our deployment files and configmaps. Right now they are very messy due to the fact that we are trying to merge multiple configmap values that are in the form of stringified json values. Because this is not natively supported we end up with very messy workarounds.

**Describe the solution you'd like**
Support merging (json) values from two configmap keys, something like:
```
  env:
    - name: my-service
      valueFrom:
        configMapKeyRef:
          name: default
          key: my-service
          type: json
    - name: my-service
      overrideStrategy: merge # default would be replace
      valueFrom:
        configMapKeyRef:
          name: overrides
          key: my-service
          type: json
```
or
```
  envFrom:
  - configMapKeyRef:
      name: default
      key: my-service
  - configMapKeyRef:
      name: overrides
      key: my-service
```

**Describe alternatives you've considered**
Alternatives include:
- using envFrom and both splitting up our configmaps as well as flattening them out (to remove stringified json values) so that we can leverage the merging that is currently supported with envFrom
