### ISSUE TITLE
Single env that uses Label Selector to find N number of config

### ISSUE THREAD

**Issue by esatterwhite** [razee-io/MustacheTemplate#296]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I have to make use of JSON in a configmap to express complex data for  a mustache template to consume

```yaml
    kind: ConfigMap
    data:
      ingress: |+
        [
          {
            "name": "foobar"
          , "tls_enabled": true
          , "tls_domain": [
              {"name": "*.{{{root_domain}}}"}
            ]
          , "tls_issuer": "abc123"
          , "annotations": []
          , "rules": [
              {
                "host": "{{{domain-one}}}"
              , "paths": [{
                  "path": "/v2/test"
                , "type": "ImplementationSpecific"
                , "service": "test-service"
                , "port": 80
                }]
              }
            , {
                "host": "{{{domain-two}}}"
              , "paths": [{
                  "path": "/v1"
                , "type": "ImplementationSpecific"
                , "service": "legacy-service"
                , "port": 80
                }]
              }
            ]
          }
        ]
```

This seems innocent, but this gets complex over time, is difficult to validate / catch bugs and you cannot do any kind of over ride on discrete values. You are left to re-define the entire json blob. We have 15+ production environments and it has gotten us in trouble several times.

In the above example if I want to change the value of one of the paths, or a port number I have to copy the entire blob around instead of setting a single key in an over rides file

**Describe the solution you'd like**

I really want a template helper that accepts a pattern, finds all matching keys in the current environment context (`envFrom`, `env`, etc), and compiles an object from that and injects that into the current data context

```yaml
kind: ConfigMap
data:
  ingress_foobar_tls_hosts_0: *.test.com 
  ingress_foobar_rules_0_host: one.test.com
  ingress_foobar_rules_0_paths_0_path: "/v1"
  ingress_foobar_rules_0_paths_0_port: 80
  ingress_foobar_rules_0_paths_0_service: service-one

  ingress_foobar_rules_0_paths_1_path: "/v2/test"
  ingress_foobar_rules_0_paths_1_port: 80
  ingress_foobar_rules_0_paths_1_service: test-service
```

This makes it pretty easy to override discrete values in complex data.

```javascript
// find all keys that look kind of like `ingress_*` and construct an object out of it
// assign that object to a key named "ingress" in template data cache
{{object_pattern "^ingress_(?:[a-z0-9])*$"}} 
```

yields

```javascript
{
  ingress: {
      foobar: {
         tls: {
           hosts: ["*.test.com"]
         }
        , rules: [
           {
             host: "one.test.com"
           , paths: [
                {path: "/v1", service: "service-one", port": 80"}
              , {path: "/v2/test", service: "test-service", port": 80"}
              ] 
           }
         ]
       }
   }
}
```

Then a mustache template can make use of this like it were inline json

```hbs
{{#each "ingress"}}
kind: Ingress
metadata:
  name: {{@key}}
rules:
  {{#each rules}}
  // build rules
  {{/each}}
{{/each}}
```

**Describe alternatives you've considered**
The assign helper. This is generally fine if you have a few simple keys.

using dots in the key is generally considered a file like key and is a little bit out of standard convention. When needing / wanting larger complex data, you have to have an assign call for every key and every nested key which is rather tedious in a template.

**Additional context**
Keeping in mind, we would like to avoid the situation of having the loop of mustache templates to generates config maps that mustache templates use. We would really like to keep config maps flat, static and obvious.

**Comment by alewitt2** [comment]
have you considered using this new feature for being able to merge json? https://github.com/razee-io/MustacheTemplate#env-overridestrategy

**Comment by esatterwhite** [comment]
@alewitt2  Yes, see the associated PR comments on #298  It has other problems

After thinking about this some more, this would be better as a key on the template like `env` or `envFrom`.

I think I want something like `jsonFrom` that matches as config map pattern and key

```yaml
jsonFrom:
  configMapPattern: "^ingress_rules"
  key: ingress
  overrideStrategy: merge
```
