### ISSUE TITLE
use data from ConfigMap with some hardcoded modifications

### ISSUE THREAD

**Issue by edmondsw** [razee-io/MustacheTemplate#360]
We have a ConfigMap with some data in it, and I want to pull that data into another ConfigMap but with a few changes to add or override some things.

I think we should be able to use overrideStrategy for this, but it currently seems to expect the override data to come from another ConfigMap, whereas I want to be able to hardcode the data I want to add/override into the mtp. To do this we would need to be able to specify a block of json or yaml instead of a configMapKeyRef

Here's an example of one of the things I tried that did not work:

```
apiVersion: deploy.razee.io/v1alpha2
kind: MustacheTemplate
metadata:
  name: test-mtp-template
  namespace: genctl
spec:
  templateEngine: handlebars
  env:
  - name: foo
    valueFrom:
      configMapKeyRef:
        name: common-config
        key: foo
        type: jsonString
  - name: foo
    overrideStrategy: merge
    foo: '{"bar": "something"}'
  strTemplates:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: foo-cm
      namespace: mynamespace
    data:
      foo: "{{{ foo }}}"
```

**Comment by alewitt2** [comment]
with the latest version of MTP https://github.com/razee-io/MustacheTemplate/releases/tag/2.1.0, i think we have a workaround for you.

instead of using value, use valueFrom, but point at some non-existant configmap. You will also need to define a default value. The only side effect from this work around, is there will be a warning message that says "couldnt find your value, we are using the default instead"

ex:

```yaml
apiVersion: deploy.razee.io/v1alpha2
kind: MustacheTemplate
metadata:
  name: test-mtp-template
  namespace: mynamespace
spec:
  templateEngine: handlebars
  env:
  - name: foo
    valueFrom:
      configMapKeyRef:
        name: common-config
        key: foo
        type: json
  - name: foo
    overrideStrategy: merge
    default: '{"bar": "something"}'
    valueFrom:
          configMapKeyRef:
            name: this-config-doesnt-exist
            key: you-cant-find-me
            type: json
  strTemplates:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: foo-cm
      namespace: mynamespace
    data:
      foo: "{{{ foo }}}"
```
