### ISSUE TITLE
Process multiple kube objects in one conditional func

### ISSUE THREAD

**Issue by ShiMing-Q** [razee-io/MustacheTemplate#457]
Using below mtp I got error 
```
razee-logs:
    error:
      b29ae44205e1e519cfa03479fc1a3a967bf60f95: expected a single document in the
        stream, but found more'
```
```
apiVersion: deploy.razee.io/v1alpha2
kind: MustacheTemplate
metadata:
  name: mtp1
spec:
  templateEngine: handlebars
  env:
    - name: version
      optional: true
      valueFrom:
        genericKeyRef:
          apiVersion: deploy.razee.io/v1alpha1
          key: version
  strTemplates:
    - |
      {{#unless version}}
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: cm1
      data: {}
      ---
      kind: ConfigMap
      apiVersion: v1
      metadata:
        name: cm2
      data: {}
      {{/unless}}
```
